### ISSUE TITLE
if the city list  size exceed the number 1000

### ISSUE THREAD

**Issue by ibmsoft** [grails-guides/grails-async-promises#1]
if the city size beyoad 1000 ,then throw error ,because the default pool is 1000
if i have data list size exceed 1000,how to do ?

**Comment by niravassar** [comment]
Use the batch concept. Break the cities list into batches of 500 and each batch could go through a async `task` with grails and call the `currentWeather` service. 

Create a method that takes the `CITIES` and every 500 creates on batch list, and work with that. 

Alternatively, you can find the setting of 1000 and increase it on the server.  I don't know exactly what or where that is, that would require some research.
